name: Make draft release

on:
  workflow_dispatch:

jobs:
  jpackage:
    name: Run JPackage
    uses: ./.github/workflows/jpackage.yml

  release:
    needs: jpackage
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/download-artifact@v4

      - name: Debug
        run: ls -lahR

      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create --draft ${{ github.ref_name }} --title ${{ github.ref_name }} artifact/.jar
